### ISSUE TITLE
表情生成抢指令

### ISSUE THREAD

**Issue by 652687791** [wuliya336/clarity-meme#2]
(TRSS崽)发送 #圣遗物列表 查原神的圣遗物列表时会抢喵喵的圣遗物列表指令
![Screenshot_2024_1217_082357](https://github.com/user-attachments/assets/a9e52c9d-bc16-4651-9292-f686320d89ff)

**Comment by shiwuliya** [comment]
`圣遗物`改成`原神圣遗物`,请使用`#清语表情更新资源`，以重载正则

**Comment by 652687791** [comment]
感谢，解决了❤️
